# Generated by Django 5.1.4 on 2025-02-23 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_chat', '0002_remove_chatmessage_user_name_chatmessage_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='user',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='user_name',
            field=models.CharField(default='anonymous', max_length=255),
            preserve_default=False,
        ),
    ]
